movieone/movie_project/movie_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("movieapp.urls")),
]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movieone/movie_project/movieapp/urls.py
from django.urls import path
from .import views
app_name='movieapp'
urlpatterns = [
    path('',views.index,name='index'),

    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),
    ]

movieone/movie_project/movieapp/models.py
from django.db import models

# Create your models here.
class movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieone/movie_project/movieapp/forms.py
from django import forms
from .models import movie
class movieform(forms.ModelForm):
    class Meta:
        model=movie
        fields=['name','desc','year','img',]

movieone/movie_project/movieapp/views.py
from django.shortcuts import render, redirect
from .models import movie
from .forms import movieform
# Create your views here.
def index(request):
    new= movie.objects.all()
    context={
        'movie_list':new
    }
    return render(request,'index.html',context)
def detail(request,movie_id):
    new1=movie.objects.get(id=movie_id)
    return render(request,'detail.html',{'movie':new1})
def add_movie(request):
    if request.method=="POST":
        name=request.POST.get('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES['img']
        movie1=movie(name=name,desc=desc,year=year,img=img,)
        movie1.save()
    return render(request,"add.html")

def update(request,id):
    movie2=movie.objects.get(id=id)
    form=movieform(request.POST or None,request.FILES,instance=movie2)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie2})
def delete(request,id):
    if request.method=='POST':
        movie3 = movie.objects.get(id=id)
        movie3.delete()
        return redirect('/')
    return render(request,'delete.html')

movieone/movie_project/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter your movie name"><br>
    <input type="text" name="desc" placeholder="Enter your movie discripition"><br>
    <input type="text" name="year" placeholder="Enter your movie year"><br>
    <input type="file" name="img"><br>
    <input type="submit">
</form>
{% endblock %}

movieone/movie_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>movie</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="#">
        <h6>ONLINE MOVIE STORE</h6>
    </a>
</nav>
{% block body %}
{% endblock%}
</body>
</html>

movieone/movie_project/templates/delete.html
<form method="POST">
    {% csrf_token %}
are you want to delete this movie
    <input type="submit">
</form>

movieone/movie_project/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
         <div class="col-md-6">
           <img src="{{movie.img.url}}" width="450" height="600"><br><br>
         </div>
               <div class="col-md-6">
                   <h5>{{movie.name}}</h5><br>
                   <h6> {{movie.desc}}</h6><br>
                   <h6> {{movie.year}}</h6><br><br>
                   <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">update </a><br><br>
                   <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">delete </a>
               </div>

    </div>
</div>
{% endblock%}

movieone/movie_project/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

movieone/movie_project/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container-fluid">

    <div class="row">

        {% for i in movie_list  %}

        <div class="col-md-2">


            <div class="card" style="width:15rem; height:27rem; ">

  <img class="card-img-top"  src="{{i.img.url}}" alt="...." width="200" height="300" >

  <div class="card-body">
    <h6 class="card-title">{{i.name}}</h6>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">{{i.name}}</a><br>
  </div>
  </div>
</div><br><br>

     {% endfor %}
    </div>

</div>
{% endblock %}